name: Runs on push to master

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build jar with dependencies
        run: mvn --batch-mode --update-snapshots verify assembly:assembly -DdescriptorId=jar-with-dependencies
      - name: Create Artifact
        uses: actions/upload-artifact@v2
        with:
          name: bluewave.jar
          path: |
            target/*-jar-with-dependencies.jar
