name: Run on every push

on: [push]


jobs:
# formatting:
#   runs-on: ubuntu-latest
#   steps:
#     - uses: actions/checkout@v2
#     - uses: axel-op/googlejavaformat-action@v3
#       with:
#         args: "--aosp --dry-run"
#         # Recommended if you use MacOS:
#         # githubToken: ${{ secrets.GITHUB_TOKEN }}
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Run Sonar
        run: GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}  mvn -e --batch-mode  clean verify sonar:sonar -Dsonar.login=${{ secrets.SONAR_TOKEN }} 
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        run: GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} mvn --batch-mode --update-snapshots verify
