CREATE SCHEMA IF NOT EXISTS APPLICATION;

CREATE TABLE APPLICATION.CONTACT (
    ID BIGSERIAL NOT NULL,
    FIRST_NAME text,
    LAST_NAME text,
    FULL_NAME text,
    GENDER text,
    DOB text,
    INFO jsonb,
    CONSTRAINT PK_CONTACT PRIMARY KEY (ID)
);


CREATE TABLE APPLICATION.USER (
    ID BIGSERIAL NOT NULL,
    USERNAME VARCHAR(255) NOT NULL UNIQUE,
    PASSWORD text NOT NULL,
    ACCESS_LEVEL integer NOT NULL,
    ACTIVE boolean NOT NULL DEFAULT true,
    CONTACT_ID bigint,
    AUTH jsonb,
    INFO jsonb,
    CONSTRAINT PK_USER PRIMARY KEY (ID)
);


CREATE TABLE APPLICATION.USER_PREFERENCE (
    ID BIGSERIAL NOT NULL,
    KEY VARCHAR(50) NOT NULL,
    VALUE text NOT NULL,
    USER_ID bigint NOT NULL,
    CONSTRAINT PK_USER_PREFERENCE PRIMARY KEY (ID)
);


CREATE TABLE APPLICATION.DASHBOARD (
    ID BIGSERIAL NOT NULL,
    NAME text NOT NULL,
    CLASS_NAME text NOT NULL,
    THUMBNAIL bytea,
    INFO jsonb,
    CONSTRAINT PK_DASHBOARD PRIMARY KEY (ID)
);


CREATE TABLE APPLICATION.DASHBOARD_USER (
    ID BIGSERIAL NOT NULL,
    USER_ID bigint NOT NULL,
    DASHBOARD_ID bigint NOT NULL,
    READ_ONLY boolean NOT NULL DEFAULT true,
    CONSTRAINT PK_DASHBOARD_USER PRIMARY KEY (ID)
);


CREATE TABLE APPLICATION.DASHBOARD_GROUP (
    ID BIGSERIAL NOT NULL,
    NAME text NOT NULL,
    DESCRIPTION text,
    USER_ID bigint NOT NULL,
    INFO jsonb,
    CONSTRAINT PK_DASHBOARD_GROUP PRIMARY KEY (ID)
);


CREATE TABLE APPLICATION.DASHBOARD_GROUP_DASHBOARD (
    DASHBOARD_GROUP_ID BIGINT NOT NULL,
    DASHBOARD_ID BIGINT NOT NULL,
    CONSTRAINT FK_DASHBOARD_GROUP_DASHBOARD FOREIGN KEY (DASHBOARD_GROUP_ID) REFERENCES APPLICATION.DASHBOARD_GROUP(ID)
        ON DELETE CASCADE ON UPDATE NO ACTION
);

ALTER TABLE APPLICATION.DASHBOARD_GROUP_DASHBOARD ADD FOREIGN KEY (DASHBOARD_ID) REFERENCES APPLICATION.DASHBOARD(ID)
    ON DELETE CASCADE ON UPDATE NO ACTION;

CREATE INDEX IDX_DASHBOARD_GROUP_DASHBOARD_DASHBOARD_GROUP_ID ON APPLICATION.DASHBOARD_GROUP_DASHBOARD(DASHBOARD_GROUP_ID);
CREATE INDEX IDX_DASHBOARD_GROUP_DASHBOARD_DASHBOARD_ID ON APPLICATION.DASHBOARD_GROUP_DASHBOARD(DASHBOARD_ID);



ALTER TABLE APPLICATION.USER ADD FOREIGN KEY (CONTACT_ID) REFERENCES APPLICATION.CONTACT(ID)
    ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE APPLICATION.USER_PREFERENCE ADD FOREIGN KEY (USER_ID) REFERENCES APPLICATION.USER(ID)
    ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE APPLICATION.DASHBOARD_USER ADD FOREIGN KEY (USER_ID) REFERENCES APPLICATION.USER(ID)
    ON DELETE CASCADE ON UPDATE NO ACTION;

ALTER TABLE APPLICATION.DASHBOARD_USER ADD FOREIGN KEY (DASHBOARD_ID) REFERENCES APPLICATION.DASHBOARD(ID)
    ON DELETE CASCADE ON UPDATE NO ACTION;

ALTER TABLE APPLICATION.DASHBOARD_GROUP ADD FOREIGN KEY (USER_ID) REFERENCES APPLICATION.USER(ID)
    ON DELETE CASCADE ON UPDATE NO ACTION;



CREATE INDEX IDX_USER_CONTACT ON APPLICATION.USER(CONTACT_ID);
CREATE INDEX IDX_USER_PREFERENCE_USER ON APPLICATION.USER_PREFERENCE(USER_ID);
CREATE INDEX IDX_DASHBOARD_USER_USER ON APPLICATION.DASHBOARD_USER(USER_ID);
CREATE INDEX IDX_DASHBOARD_USER_DASHBOARD ON APPLICATION.DASHBOARD_USER(DASHBOARD_ID);
CREATE INDEX IDX_DASHBOARD_GROUP_USER ON APPLICATION.DASHBOARD_GROUP(USER_ID);
